version: "3.7"


services:

  db:
    image: postgres:12
    container_name: db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5444:5432"
    networks:
      - net1
    volumes:
      - db_home:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=v15_odoo

  odoo:
    container_name: odoo
    image: odoogap:15.0
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - odoo_home:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ~/git/oe/15.0/:/mnt/ee-addons
    depends_on:
      - db
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8072:8072"
    networks:
      - net1
      
  odoo_init:
    container_name: odoo_init
    image: odoogap:15.0
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'no'
    command: >
      bash -c "if [ ! -d "/var/lib/odoo/started" ]; then touch /var/lib/odoo/started
      && /entrypoint.sh odoo -d v15_odoo -i base --max-cron-threads 0 --no-http --stop-after-init -i base; fi"
    volumes:
      - odoo_home:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ~/git/oe/15.0/:/mnt/ee-addons
    depends_on:
      - db
    networks:
      - net1


volumes:
  db_home:
    external: false
  odoo_home:
    external: false


networks:
  net1: 
    name: net1
